import fs from 'fs';
import path from 'path';

/** ASS colours are &HAABBGGRR — alpha first, then blue, green, red. */
function assColor(hex, alphaHex = '00') {
  const m = /^#?([0-9a-f]{6})$/i.exec(String(hex).trim());
  const rgb = m ? m[1] : 'FFFFFF';
  const r = rgb.slice(0, 2), g = rgb.slice(2, 4), b = rgb.slice(4, 6);
  return `&H${alphaHex}${b}${g}${r}`.toUpperCase();
}

function assTime(ms) {
  const total = Math.max(0, Math.round(ms));
  const cs = Math.floor((total % 1000) / 10);
  const s = Math.floor(total / 1000) % 60;
  const m = Math.floor(total / 60000) % 60;
  const h = Math.floor(total / 3600000);
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

function escapeText(text) {
  return String(text)
    .replace(/\\/g, '/')
    .replace(/[{}]/g, m => (m === '{' ? '(' : ')'))
    .replace(/\r?\n/g, '\\N')
    .trim();
}

const normalize = (s) => s.toLowerCase().replace(/[^a-z0-9À-ɏ]/gi, '');

/**
 * Pair each whitespace token of the written line with the TTS word timings.
 *
 * The service reports words stripped of punctuation, so highlighting its
 * tokens directly renders "Now you how old" where the script said
 * "Now you. how old." A token can also be spoken as several words ("2026" ->
 * "twenty twenty six"), so each written token absorbs TTS words until it is
 * covered. If the two sequences cannot be reconciled we return null and the
 * caller falls back to a plain, un-highlighted line — a correct caption with no
 * sweep beats a sweep on mangled text.
 */
function alignTokens(text, words) {
  const tokens = String(text).trim().split(/\s+/).filter(Boolean);
  if (!tokens.length || !words.length) return null;

  const out = [];
  let wi = 0;

  for (const token of tokens) {
    const core = normalize(token);
    if (!core) {                       // standalone punctuation: glue to previous
      if (out.length) out[out.length - 1].token += ` ${token}`;
      continue;
    }
    const consumed = [];
    let acc = '';
    while (wi < words.length && acc.length < core.length) {
      acc += normalize(words[wi].text);
      consumed.push(words[wi]);
      wi++;
    }
    if (!consumed.length || !acc.startsWith(core.slice(0, Math.min(3, core.length)))) return null;
    out.push({
      token,
      startMs: consumed[0].startMs,
      endMs: consumed[consumed.length - 1].endMs,
    });
  }
  // Leftover spoken words mean the alignment drifted somewhere in the middle.
  return wi >= words.length - 1 ? out : null;
}

/**
 * Build the karaoke override string for one spoken line.
 *
 * Word boundaries come back from the TTS service, so the highlight lands on the
 * exact word being pronounced — which is the whole point for a learner reading
 * along. Gaps between words are folded into the preceding token so the sweep
 * never stalls mid-line.
 */
function karaokeText(line) {
  const display = line.caption || line.text;
  const words = (line.words || []).filter(w => w.text && w.text.trim());
  const aligned = words.length ? alignTokens(display, words) : null;
  if (!aligned) return null;

  const parts = [];
  const lead = Math.max(0, aligned[0].startMs - line.startMs);
  if (lead > 30) parts.push(`{\\kf${Math.round(lead / 10)}}`);

  aligned.forEach((tok, i) => {
    const next = aligned[i + 1];
    // The clip's own trailing silence is part of line.endMs; letting the last
    // token sweep all the way there leaves the highlight crawling in silence.
    const end = next ? next.startMs : Math.min(line.endMs, tok.endMs + 250);
    const durCs = Math.max(1, Math.round((end - tok.startMs) / 10));
    parts.push(`{\\kf${durCs}}${escapeText(tok.token)}${next ? ' ' : ''}`);
  });
  return parts.join('');
}

const HEADER = ({ width, height, fonts, accent }) => `[Script Info]
; Generated by English Every Day
ScriptType: v4.00+
PlayResX: ${width}
PlayResY: ${height}
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: EN,${fonts.en},64,${assColor(accent)},${assColor('#FFFFFF')},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,0,0,1,3.4,1.4,2,220,220,168,1
Style: ENPLAIN,${fonts.en},64,${assColor('#FFFFFF')},${assColor('#FFFFFF')},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,0,0,1,3.4,1.4,2,220,220,168,1
Style: AR,${fonts.ar},46,${assColor('#CBD5E1')},${assColor('#CBD5E1')},${assColor('#000000')},${assColor('#000000', '80')},0,0,0,0,100,100,0,0,1,2.6,1,2,220,220,86,1
Style: CUE,${fonts.en},56,${assColor(accent)},${assColor(accent)},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,2,0,1,3.2,1,2,220,220,312,1
Style: OPTS,${fonts.en},52,${assColor('#FFFFFF')},${assColor('#FFFFFF')},${assColor('#000000')},${assColor('#000000', '60')},0,0,0,0,100,100,0,0,1,3,1,2,300,300,120,1
Style: NOTE,${fonts.en},40,${assColor('#94A3B8')},${assColor('#94A3B8')},${assColor('#000000')},${assColor('#000000', '80')},0,0,0,0,100,100,0,0,1,2.4,1,8,220,220,60,1
Style: SPK,${fonts.en},36,${assColor(accent)},${assColor(accent)},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,3,0,1,2.4,1,1,224,220,258,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

function dialogue({ start, end, style, text, layer = 0, effect = '' }) {
  return `Dialogue: ${layer},${assTime(start)},${assTime(end)},${style},,0,0,0,${effect},${text}`;
}

/**
 * @param {Array} timeline  lines from assembleVoiceTrack, each optionally with
 *                          { ar, captions: 'karaoke'|'plain'|'none', note }
 * @param {Array} cues      [{ startMs, endMs, text }] shown during silences
 */
export function buildAss(timeline, { outFile, width, height, fonts, accent, cues = [] }) {
  const events = [];

  for (const line of timeline) {
    const mode = line.captions || 'karaoke';

    // A short tail keeps the line on screen through the pause that follows it,
    // instead of snapping away the instant the voice stops. When a practice cue
    // is about to appear the tail is cut short so the two never share the frame.
    const pause = line.pauseAfterMs ?? 0;
    const tail = line.cue ? Math.min(pause / 4, 220) : Math.min(pause, 700);
    const start = line.startMs;
    const end = line.endMs + tail;

    // A "none" line is a deliberate ears-only beat — the listening pass where
    // showing the words would defeat the exercise. It must still not black the
    // frame out: the earlier build emitted nothing at all here and left 88
    // seconds of empty screen, which is where the average view died. The
    // speaker label and the section note reveal none of the dialogue, so they
    // stay, and only the caption and its translation are withheld.
    if (mode !== 'none') {
      const sweep = mode === 'karaoke' ? karaokeText(line) : null;
      if (sweep) {
        events.push(dialogue({ start, end, style: 'EN', text: sweep }));
      } else {
        events.push(dialogue({ start, end, style: 'ENPLAIN', text: escapeText(line.caption || line.text) }));
      }

      if (line.ar) {
        events.push(dialogue({ start, end, style: 'AR', text: escapeText(line.ar) }));
      }
    }
    if (line.speakerName) {
      events.push(dialogue({ start, end, style: 'SPK', text: escapeText(line.speakerName) }));
    }
    if (line.note) {
      events.push(dialogue({ start, end, style: 'NOTE', text: escapeText(line.note) }));
    }
  }

  for (const cue of cues) {
    // A multi-line cue is an answer block (A / B / C), not a one-line prompt:
    // it needs the smaller, quieter style so three lines still fit the band.
    const multiline = /\n/.test(cue.text);
    events.push(dialogue({
      start: cue.startMs, end: cue.endMs, style: multiline ? 'OPTS' : 'CUE', layer: 1,
      // gentle pulse so a silent gap does not look like a frozen video
      text: `{\\fad(220,220)}${escapeText(cue.text)}`,
    }));
  }

  const body = HEADER({ width, height, fonts, accent }) + events.join('\n') + '\n';
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, 'utf8');
  return outFile;
}

/** Plain SRT of the English track, for upload as a real caption file. */
export function buildSrt(timeline, outFile, { field = 'text' } = {}) {
  const lines = timeline.filter(l => (l.captions || 'karaoke') !== 'none' && l[field]);
  const body = lines.map((l, i) => {
    const toSrt = (ms) => assTime(ms).replace('.', ',').padStart(11, '0')
      .replace(/^(\d):/, '0$1:') + '0';
    return `${i + 1}\n${toSrt(l.startMs)} --> ${toSrt(l.endMs + Math.min(l.pauseAfterMs ?? 0, 700))}\n${l[field]}\n`;
  }).join('\n');
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, 'utf8');
  return outFile;
}
