import fs from 'fs';
import path from 'path';

/** ASS colours are &HAABBGGRR — alpha first, then blue, green, red. */
function assColor(hex, alphaHex = '00') {
  const m = /^#?([0-9a-f]{6})$/i.exec(String(hex).trim());
  const rgb = m ? m[1] : 'FFFFFF';
  const r = rgb.slice(0, 2), g = rgb.slice(2, 4), b = rgb.slice(4, 6);
  return `&H${alphaHex}${b}${g}${r}`.toUpperCase();
}

function assTime(ms) {
  const total = Math.max(0, Math.round(ms));
  const cs = Math.floor((total % 1000) / 10);
  const s = Math.floor(total / 1000) % 60;
  const m = Math.floor(total / 60000) % 60;
  const h = Math.floor(total / 3600000);
  return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(cs).padStart(2, '0')}`;
}

function escapeText(text) {
  return String(text)
    .replace(/\\/g, '/')
    .replace(/[{}]/g, m => (m === '{' ? '(' : ')'))
    .replace(/\r?\n/g, '\\N')
    .trim();
}

/**
 * Build the karaoke override string for one spoken line.
 *
 * Word boundaries come back from the TTS service, so the highlight lands on the
 * exact syllable being pronounced — which is the whole point for a learner
 * following along. Gaps between words are folded into the preceding word so
 * the sweep never stalls mid-line.
 */
function karaokeText(line) {
  const words = (line.words || []).filter(w => w.text && w.text.trim());
  if (!words.length) return escapeText(line.text);

  const parts = [];
  const lead = Math.max(0, words[0].startMs - line.startMs);
  if (lead > 30) parts.push(`{\\kf${Math.round(lead / 10)}}`);

  words.forEach((w, i) => {
    const next = words[i + 1];
    const end = next ? next.startMs : Math.max(w.endMs, line.endMs);
    const durCs = Math.max(1, Math.round((end - w.startMs) / 10));
    const token = escapeText(w.text);
    // Punctuation arrives glued to the word; keep it inside the same sweep.
    parts.push(`{\\kf${durCs}}${token}${next ? ' ' : ''}`);
  });
  return parts.join('');
}

const HEADER = ({ width, height, fonts, accent }) => `[Script Info]
; Generated by English Every Day
ScriptType: v4.00+
PlayResX: ${width}
PlayResY: ${height}
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: EN,${fonts.en},64,${assColor(accent)},${assColor('#FFFFFF')},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,0,0,1,3.4,1.4,2,220,220,168,1
Style: ENPLAIN,${fonts.en},64,${assColor('#FFFFFF')},${assColor('#FFFFFF')},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,0,0,1,3.4,1.4,2,220,220,168,1
Style: AR,${fonts.ar},46,${assColor('#CBD5E1')},${assColor('#CBD5E1')},${assColor('#000000')},${assColor('#000000', '80')},0,0,0,0,100,100,0,0,1,2.6,1,2,220,220,86,1
Style: CUE,${fonts.en},52,${assColor(accent)},${assColor(accent)},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,2,0,1,3,1,2,220,220,168,1
Style: NOTE,${fonts.en},40,${assColor('#94A3B8')},${assColor('#94A3B8')},${assColor('#000000')},${assColor('#000000', '80')},0,0,0,0,100,100,0,0,1,2.4,1,8,220,220,60,1
Style: SPK,${fonts.en},36,${assColor(accent)},${assColor(accent)},${assColor('#000000')},${assColor('#000000', '80')},-1,0,0,0,100,100,3,0,1,2.4,1,1,224,220,258,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;

function dialogue({ start, end, style, text, layer = 0, effect = '' }) {
  return `Dialogue: ${layer},${assTime(start)},${assTime(end)},${style},,0,0,0,${effect},${text}`;
}

/**
 * @param {Array} timeline  lines from assembleVoiceTrack, each optionally with
 *                          { ar, captions: 'karaoke'|'plain'|'none', note }
 * @param {Array} cues      [{ startMs, endMs, text }] shown during silences
 */
export function buildAss(timeline, { outFile, width, height, fonts, accent, cues = [] }) {
  const events = [];

  for (const line of timeline) {
    const mode = line.captions || 'karaoke';
    if (mode === 'none') continue;

    // A short tail keeps the line on screen through the pause that follows it,
    // instead of snapping away the instant the voice stops.
    const tail = Math.min(line.pauseAfterMs ?? 0, 700);
    const start = line.startMs;
    const end = line.endMs + tail;

    if (mode === 'karaoke') {
      events.push(dialogue({ start, end, style: 'EN', text: karaokeText(line) }));
    } else {
      events.push(dialogue({ start, end, style: 'ENPLAIN', text: escapeText(line.text) }));
    }

    if (line.ar) {
      events.push(dialogue({ start, end, style: 'AR', text: escapeText(line.ar) }));
    }
    if (line.speakerName) {
      events.push(dialogue({ start, end, style: 'SPK', text: escapeText(line.speakerName) }));
    }
    if (line.note) {
      events.push(dialogue({ start, end, style: 'NOTE', text: escapeText(line.note) }));
    }
  }

  for (const cue of cues) {
    events.push(dialogue({
      start: cue.startMs, end: cue.endMs, style: 'CUE', layer: 1,
      // gentle pulse so a silent gap does not look like a frozen video
      text: `{\\fad(220,220)}${escapeText(cue.text)}`,
    }));
  }

  const body = HEADER({ width, height, fonts, accent }) + events.join('\n') + '\n';
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, 'utf8');
  return outFile;
}

/** Plain SRT of the English track, for upload as a real caption file. */
export function buildSrt(timeline, outFile, { field = 'text' } = {}) {
  const lines = timeline.filter(l => (l.captions || 'karaoke') !== 'none' && l[field]);
  const body = lines.map((l, i) => {
    const toSrt = (ms) => assTime(ms).replace('.', ',').padStart(11, '0')
      .replace(/^(\d):/, '0$1:') + '0';
    return `${i + 1}\n${toSrt(l.startMs)} --> ${toSrt(l.endMs + Math.min(l.pauseAfterMs ?? 0, 700))}\n${l[field]}\n`;
  }).join('\n');
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, body, 'utf8');
  return outFile;
}
